const error_handler = (error,req, res, next) => {
    console.error("Error interno:", error);
    
    return res.status(500).json({
        sucess: false,
        response: error,
        message: "Â¡Oops! Ha ocurrido un error interno en el servidor. ðŸ˜ž",
})
}


export default error_handler